# Generated by Django 5.1.7 on 2025-03-17 15:33

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='event_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.upload_to),
        ),
    ]
